"""Assets stage: draft-image generation.

Default backend is **Nano Banana** (Gemini 2.5 Flash Image) via its reference/
edit endpoint: each beat is generated by transferring the Deep Root Lore ink
style from approved reference images (``references/`` via ``references.json``)
onto a clean scene prompt. No LoRA, so no baked-in subject contamination
(the manananggal woman / wings / bamboo huts). Optional per-beat character
references (``Shot.references``) keep recurring characters consistent.

Fallback backends: base flux + STYLE_BLOCK (``--backend flux``) or the trained
LoRA (``--backend flux-lora``).

CLI:
    python -m src.assets                   # all beats, Nano Banana
    python -m src.assets --scene s004      # one beat
    python -m src.assets --backend flux    # base flux + style block
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import fal_client
import requests

from . import config
from .manifest import Shot, Storyboard, load, save

DEFAULT_VARIATIONS = 3
DEFAULT_BACKEND = "nano"
STYLE_REF = "style"  # implicit style reference applied to every Nano Banana beat

NANO_ENDPOINT = "fal-ai/nano-banana/edit"
LORA_ENDPOINT = "fal-ai/flux-lora"
BASE_ENDPOINT = "fal-ai/flux/dev"
IMAGE_SIZE = "landscape_16_9"

# Instruction that turns Nano Banana's edit endpoint into style-transfer: match
# the reference's STYLE, invent a new scene, never copy the reference's subjects.
NANO_STYLE_INSTRUCTION = (
    "Study the art style of the reference image(s): ink-and-watercolor graphic-novel "
    "illustration, heavy black ink linework and cross-hatching, muted earth-tone "
    "watercolor washes, warm amber candlelight against deep near-black shadow, strong "
    "chiaroscuro, aged paper grain, cinematic 16:9. Do NOT reuse the subjects, "
    "characters, or setting of the reference images. Create a brand-new illustration "
    "in that exact style showing: "
)

# Style anchor for the flux fallback backend.
STYLE_BLOCK = (
    "A dark folkloric horror illustration in ink and watercolor, heavy black ink "
    "linework with loose expressive cross-hatching, muted earth-tone watercolor "
    "washes, warm amber candlelight glowing against deep near-black shadow, strong "
    "chiaroscuro, aged paper grain, desaturated moody palette, cinematic 16:9"
)


# --- reference registry -----------------------------------------------------
def load_references() -> dict:
    if config.REFERENCES_CONFIG.exists():
        return json.loads(config.REFERENCES_CONFIG.read_text(encoding="utf-8"))
    return {}


def _save_references(reg: dict) -> None:
    config.REFERENCES_CONFIG.write_text(json.dumps(reg, indent=2) + "\n", encoding="utf-8")


def ref_urls(names: list[str]) -> list[str]:
    """Resolve reference names -> fal image URLs, uploading + caching as needed."""
    reg = load_references()
    urls: list[str] = []
    changed = False
    for name in names:
        entry = reg.get(name)
        if not entry:
            continue
        files = entry.get("files") or ([entry["file"]] if entry.get("file") else [])
        cached = entry.get("urls") or []
        if len(cached) != len(files):  # (re)upload if not cached for all files
            cached = [fal_client.upload_file(str(config.REFERENCES_DIR / f)) for f in files]
            entry["files"], entry["urls"] = files, cached
            changed = True
        urls.extend(cached)
    if changed:
        _save_references(reg)
    return urls


# --- generation backends ----------------------------------------------------
def _generate_nano(scene_prompt: str, image_urls: list[str], n: int) -> list[str]:
    """Nano Banana edit: style-transfer the references onto a new scene, n times."""
    prompt = NANO_STYLE_INSTRUCTION + scene_prompt
    out: list[str] = []
    for _ in range(n):  # one image per call -> n distinct variations
        result = fal_client.subscribe(
            NANO_ENDPOINT,
            arguments={"prompt": prompt, "image_urls": image_urls, "aspect_ratio": "16:9"},
            with_logs=False,
        )
        images = result.get("images") or []
        if images:
            out.append(images[0]["url"])
    return out


def load_lora() -> dict | None:
    if not config.LORA_CONFIG.exists():
        return None
    data = json.loads(config.LORA_CONFIG.read_text(encoding="utf-8"))
    return data if data.get("lora_url") else None


def style_prompt(prompt: str, lora: dict | None) -> str:
    """Anchor style for the flux backends: LoRA trigger, or a leading STYLE_BLOCK."""
    if not lora:
        return f"{STYLE_BLOCK}. {prompt}"
    trigger = (lora.get("trigger_word") or "").strip()
    if trigger and trigger.lower() not in prompt.lower():
        return f"{trigger} {prompt}"
    return prompt


def _generate_flux(prompt: str, n: int, lora: dict | None) -> list[str]:
    if lora:
        endpoint = lora.get("inference_endpoint", LORA_ENDPOINT)
        args = {
            "prompt": prompt,
            "loras": [{"path": lora["lora_url"], "scale": 1.0}],
            "num_images": n,
            "image_size": IMAGE_SIZE,
            "num_inference_steps": 28,
            "guidance_scale": 3.5,
            "enable_safety_checker": False,
            "output_format": "png",
        }
    else:
        endpoint = BASE_ENDPOINT
        args = {
            "prompt": prompt,
            "num_images": n,
            "image_size": IMAGE_SIZE,
            "num_inference_steps": 28,
            "guidance_scale": 3.5,
            "enable_safety_checker": False,
        }
    result = fal_client.subscribe(endpoint, arguments=args, with_logs=False)
    return [img["url"] for img in result.get("images", [])]


def _download(url: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    resp = requests.get(url, timeout=180)
    resp.raise_for_status()
    dest.write_bytes(resp.content)


def generate_for_shot(
    shot: Shot, n: int, backend: str = DEFAULT_BACKEND, lora: dict | None = None
) -> list[str]:
    """Generate + download n draft variations for one beat; record their paths."""
    if backend == "nano":
        urls = ref_urls([STYLE_REF, *(shot.references or [])])
        if not urls:
            raise RuntimeError(
                "No references resolved — populate references.json with a 'style' entry."
            )
        gen_urls = _generate_nano(shot.prompt, urls, n)
    else:
        if lora is None and backend == "flux-lora":
            lora = load_lora()
        gen_urls = _generate_flux(style_prompt(shot.prompt, lora), n, lora)

    rel_paths: list[str] = []
    for i, url in enumerate(gen_urls):
        dest = config.ASSETS / shot.scene_id / f"var_{i}.png"
        _download(url, dest)
        rel_paths.append(str(dest.relative_to(config.ROOT)).replace("\\", "/"))
    shot.draft_variations = rel_paths
    return rel_paths


def generate_drafts(
    storyboard: Storyboard,
    n: int = DEFAULT_VARIATIONS,
    only: set[str] | None = None,
    limit: int | None = None,
    backend: str = DEFAULT_BACKEND,
    skip_existing: bool = True,
    save_after_each: bool = False,
) -> Storyboard:
    """Generate draft variations for some or all beats. Mutates the storyboard.

    Resilient for long batches: skips beats that already have drafts, tolerates a
    single beat failing, and can persist after each beat.
    """
    config.require_for("assets")

    shots = storyboard.shots
    if only:
        shots = [s for s in shots if s.scene_id in only]
    if limit:
        shots = shots[:limit]

    failures: list[str] = []
    for shot in shots:
        if skip_existing and shot.draft_variations:
            print(f"{shot.scene_id}: already has {len(shot.draft_variations)} drafts — skipping.")
            continue
        try:
            print(f"Generating {n} drafts for {shot.scene_id} ({backend}) ...")
            paths = generate_for_shot(shot, n, backend=backend)
            print(f"  -> {len(paths)} images")
        except Exception as exc:
            print(f"  !! {shot.scene_id} FAILED: {exc}")
            failures.append(shot.scene_id)
        if save_after_each:
            save(storyboard)

    if failures:
        print(f"\nFailed beats ({len(failures)}): {failures} — re-run to retry just these.")
    return storyboard


def _main() -> None:
    parser = argparse.ArgumentParser(description="Deep Root Lore draft-image stage.")
    parser.add_argument("--scene", nargs="*", help="scene id(s) to generate (default: all).")
    parser.add_argument("--variations", type=int, default=DEFAULT_VARIATIONS)
    parser.add_argument("--limit", type=int, default=None, help="cap number of beats.")
    parser.add_argument("--backend", default=DEFAULT_BACKEND, choices=["nano", "flux", "flux-lora"])
    parser.add_argument("--force", action="store_true", help="regenerate beats that already have drafts.")
    args = parser.parse_args()

    storyboard = load()
    if not storyboard.shots:
        raise SystemExit("Manifest has no beats — run the script stage first.")

    print(f"Backend: {args.backend}")
    generate_drafts(
        storyboard,
        n=args.variations,
        only=set(args.scene) if args.scene else None,
        limit=args.limit,
        backend=args.backend,
        skip_existing=not args.force,
        save_after_each=True,
    )
    save(storyboard)
    print(f"Saved draft variations into {config.MANIFEST_PATH}")


if __name__ == "__main__":
    _main()
